spring:
  application:
    name: DockerExample
info:
  version: "1.1"
  build: "001"
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
services:
  commerce: SpringCommerce  
  
    

