version: '3'

services:
    my_mongo:
      image: mongo:latest
      ports:
        - "27018:27017"
    
    skills-service:
      container_name: skills
      build: 
        context: .
        dockerfile: ./src/main/docker/Dockerfile
      ports:
       - '80:8080'
 
    
     