node {
  
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/tamizhmani2000/awslearn.git'

   }
   stage('Build') {


         sh "'./DockerExample/gradlew' build"
  
   }
   stage('Results') {
      echo 'completed'
   }
}